### ISSUE TITLE
test demo build error

### ISSUE THREAD

**Issue by RockyRori** [mrproliu/go-agent-instrumentation#1]
### Description

After cloning this project , I want to witness the result of go-agent-instrumentation.

I simply used provided makefile, whereas it didn't work as expected.

go build error appeared , I'm a junior developer looking for your help.

### Environment
OS: [Linux]

Architecture: [x86_64]

Go Version: [1.20.1 linux/amd64]

go-agent-instrumentation version: [main, https://github.com/mrproliu/go-agent-instrumentation/commit/989e374980575d68f330748c2aeb88efa2422fad]

### Steps To Reproduce

![make test](https://github.com/mrproliu/go-agent-instrumentation/assets/45476371/ee588f6c-e2e4-4818-b717-eede76b3e1b9)

### Expected behavior

No error, build succeed.

**Comment by RockyRori** [comment]
因为读到你的论文才了解到这个项目，如果方便可用中文交流。

**Comment by mrproliu** [comment]
可以使用中文交流。

这个是测试项目，我使用MacOS进行编译和执行。在使用MacOS测试时，他会在当前用户的桌面目录中创建go-agent-instrument.txt以记录toolchain的参数信息。你可以[在这里将目录](https://github.com/mrproliu/go-agent-instrumentation/blob/989e374980575d68f330748c2aeb88efa2422fad/cmd/main.go#L35-L45)更改/删除后再次尝试。

**Comment by RockyRori** [comment]
> 可以使用中文交流。
> 
> 这个是测试项目，我使用MacOS进行编译和执行。在使用MacOS测试时，他会在当前用户的桌面目录中创建go-agent-instrument.txt以记录toolchain的参数信息。你可以[在这里将目录](https://github.com/mrproliu/go-agent-instrumentation/blob/989e374980575d68f330748c2aeb88efa2422fad/cmd/main.go#L35-L45)更改/删除后再次尝试。

感谢，修改go-agent-instrument.txt地址后，在Linux系统上构建成功，并且在控制台看到了变化。
Windows系统上无构建报错，go-agent-instrument.txt有内容，但是对Gin的自动增强改动未生效。

**Comment by mrproliu** [comment]
这个我没有尝试过，您可以本地debug改一下试试…另外需要注意的是，当前已经开源出[skywalking-go](https://github.com/apache/skywalking-go)项目，他提供了更复杂的功能，当然，实现原理也会更复杂。

**Comment by mrproliu** [comment]
如果没有什么问题，我就先把issue关闭了。如果您那边有什么问题或者对该问题有最近的进展，欢迎reopen或者create issue.

**Comment by RockyRori** [comment]
> 如果没有什么问题，我就先把issue关闭了。如果您那边有什么问题或者对该问题有最近的进展，欢迎reopen或者create issue.

感谢您，问题已经解决。
