### ISSUE TITLE
missing interceptor result

### ISSUE THREAD

**Issue by RockyRori** [mrproliu/go-agent-instrumentation#2]
### Description

After building test with command -toolexec, lack interceptor result.

Page and console remained the same as normal go build.

### Environment
OS: [Windows 10]

Architecture: [x86_64]

Go Version: [1.20.1 windows/amd64]

go-agent-instrumentation version: [main, https://github.com/mrproliu/go-agent-instrumentation/commit/989e374980575d68f330748c2aeb88efa2422fad]

### Steps To Reproduce

![gotoolexec](https://github.com/mrproliu/go-agent-instrumentation/assets/45476371/b33481af-5619-4088-a6e5-af792573bff6)
![page](https://github.com/mrproliu/go-agent-instrumentation/assets/45476371/06838a9a-a20c-4975-bbe8-87f2b7a74bfb)

### Expected behavior

Page content changed or Console print some messages.

**Comment by mrproliu** [comment]
Please keep one issue for discussion.
